// eslint-disable-next-line @typescript-eslint/no-unused-expressions
[{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'href'.",
	"source": "ts",
	"startLineNumber": 130,
	"startColumn": 25,
	"endLineNumber": 130,
	"endColumn": 29,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type '\"\" | { project: { title: string; subtitle: string; description: string; image: string; tech: string[]; category: string; siteUrl: string; repoUrl: string; }; \"\": any; }' is not assignable to type 'ReactNode'.\n  Object literal may only specify known properties, and 'project' does not exist in type 'ReactElement<any, string | JSXElementConstructor<any>> | Iterable<ReactNode> | ReactPortal'.",
	"source": "ts",
	"startLineNumber": 130,
	"startColumn": 31,
	"endLineNumber": 130,
	"endColumn": 38,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "eslint5",
	"severity": 8,
	"message": "Parsing error: ',' expected.",
	"source": "eslint",
	"startLineNumber": 130,
	"startColumn": 37,
	"endLineNumber": 130,
	"endColumn": 37,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 130,
	"startColumn": 38,
	"endLineNumber": 130,
	"endColumn": 39,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "')' expected.",
	"source": "ts",
	"startLineNumber": 131,
	"startColumn": 25,
	"endLineNumber": 131,
	"endColumn": 31,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 134,
	"startColumn": 23,
	"endLineNumber": 134,
	"endColumn": 24,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "17002",
	"severity": 8,
	"message": "Expected corresponding JSX closing tag for 'div'.",
	"source": "ts",
	"startLineNumber": 137,
	"startColumn": 25,
	"endLineNumber": 137,
	"endColumn": 26,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 138,
	"startColumn": 22,
	"endLineNumber": 138,
	"endColumn": 23,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'href'.",
	"source": "ts",
	"startLineNumber": 141,
	"startColumn": 25,
	"endLineNumber": 141,
	"endColumn": 29,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type '\"\" | { project: { title: string; subtitle: string; description: string; image: string; tech: string[]; category: string; siteUrl: string; repoUrl: string; }; \"\": any; }' is not assignable to type 'ReactNode'.\n  Object literal may only specify known properties, and 'project' does not exist in type 'ReactElement<any, string | JSXElementConstructor<any>> | Iterable<ReactNode> | ReactPortal'.",
	"source": "ts",
	"startLineNumber": 141,
	"startColumn": 31,
	"endLineNumber": 141,
	"endColumn": 38,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 141,
	"startColumn": 38,
	"endLineNumber": 141,
	"endColumn": 39,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "')' expected.",
	"source": "ts",
	"startLineNumber": 142,
	"startColumn": 25,
	"endLineNumber": 142,
	"endColumn": 31,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 145,
	"startColumn": 23,
	"endLineNumber": 145,
	"endColumn": 24,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "17002",
	"severity": 8,
	"message": "Expected corresponding JSX closing tag for 'div'.",
	"source": "ts",
	"startLineNumber": 148,
	"startColumn": 25,
	"endLineNumber": 148,
	"endColumn": 26,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 149,
	"startColumn": 22,
	"endLineNumber": 149,
	"endColumn": 23,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "')' expected.",
	"source": "ts",
	"startLineNumber": 151,
	"startColumn": 17,
	"endLineNumber": 151,
	"endColumn": 19,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 153,
	"startColumn": 15,
	"endLineNumber": 153,
	"endColumn": 16,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 161,
	"startColumn": 13,
	"endLineNumber": 161,
	"endColumn": 14,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "17002",
	"severity": 8,
	"message": "Expected corresponding JSX closing tag for 'div'.",
	"source": "ts",
	"startLineNumber": 163,
	"startColumn": 15,
	"endLineNumber": 163,
	"endColumn": 16,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "17002",
	"severity": 8,
	"message": "Expected corresponding JSX closing tag for 'section'.",
	"source": "ts",
	"startLineNumber": 164,
	"startColumn": 13,
	"endLineNumber": 164,
	"endColumn": 16,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "')' expected.",
	"source": "ts",
	"startLineNumber": 166,
	"startColumn": 9,
	"endLineNumber": 166,
	"endColumn": 11,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'div'.",
	"source": "ts",
	"startLineNumber": 166,
	"startColumn": 11,
	"endLineNumber": 166,
	"endColumn": 14,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 167,
	"startColumn": 7,
	"endLineNumber": 167,
	"endColumn": 9,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'div'.",
	"source": "ts",
	"startLineNumber": 167,
	"startColumn": 9,
	"endLineNumber": 167,
	"endColumn": 12,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 168,
	"startColumn": 5,
	"endLineNumber": 168,
	"endColumn": 7,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "2552",
	"severity": 8,
	"message": "Cannot find name 'section'. Did you mean 'Selection'?",
	"source": "ts",
	"startLineNumber": 168,
	"startColumn": 7,
	"endLineNumber": 168,
	"endColumn": 14,
	"relatedInformation": [
		{
			"startLineNumber": 35060,
			"startColumn": 13,
			"endLineNumber": 35060,
			"endColumn": 22,
			"message": "'Selection' is declared here.",
			"resource": "/d:/vs code/Microsoft VS Code/e7fb5e96c0/resources/app/extensions/node_modules/typescript/lib/lib.dom.d.ts"
		}
	],
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 169,
	"startColumn": 3,
	"endLineNumber": 169,
	"endColumn": 4,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "1128",
	"severity": 8,
	"message": "Declaration or statement expected.",
	"source": "ts",
	"startLineNumber": 170,
	"startColumn": 1,
	"endLineNumber": 170,
	"endColumn": 2,
	"modelVersionId": 7,
	"origin": "extHost1"
},{
	"resource": "/d:/Mahmoud Rady - Portfolio/src/components/Projects.tsx",
	"owner": "typescript",
	"code": "6133",
	"severity": 4,
	"message": "'React' is declared but its value is never read.",
	"source": "ts",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 27,
	"modelVersionId": 7,
	"tags": [
		1
	],
	"origin": "extHost1"
}]